### ISSUE TITLE
Design impressions from a noob who feels forced to updoot to quelpa or straight

### ISSUE THREAD

**Issue by SylvianHemus** [radian-software/straight.el#1041]
I'm aware of this package because there are a number of projects using it and I'm beginning to feel like I'm forced to use quelpa or straight. Admittedly, I'm not a fan of ELPA, MELPA, etc and their political circlejerking, so I enjoy the general gestalt of this package (e.g., using git rather than tarballs and using git repos rather than gatekeeping tarball resources based on the kind of license they use or other contingent irrelevant wankery)

Here is why I feel like I'm not really interested in having to use this and would rather just manually download .el files and load-path

From my perspective, requiring a package is simple. It's one line.
Load path is simple. One line

It feels like to use your new system, I have to
- use bootstrap, even if I don't want to (because it is opinionated)
- use git, even if I don't want to (E.g., I want to use a different VC or a different cli tool)
- use emacs 25 or higher, even if I don't want to
- use very verbose elisp to update and manage packages

It is cool to be able to use git for emacs. But is it really necessary? And is it worth the trade-off of complexity that this package introduces? I feel like this kind of development is too similar to webdev and to the npm ecosystem, which I'm not entirely fond of socially.

For a systems design allegedly for ``emacs hackers'', this feels very constrained. Moreover, hacking does not refer to the basic usage of a system or customization thereof. That's just called using a computer.  

Respect for what you've made but wanted to voice this opinion. What I would like to see as a user is a much less complex set of initial setup instructions, compatibility with package.el (so I don't need to redo everything I already have set up), and intended compatibility with older forms of emacs as well as other VCS etc

**Comment by progfolio** [comment]
>  I'm beginning to feel like I'm forced to use quelpa or straight

Use whatever tools work for you.

> From my perspective, requiring a package is simple. It's one line. Load path is simple. One line

That is simple, and it may work for simple packages. However, it will not workfor more complex packages.
You'll have to manually manage package dependencies, for one (that alone is a pain, IMO).
There are also a number of other steps involved in building packages. e.g. byte-compilation, generating autoloads, installing info files, etc. Straight handles all of this and makes it easy to configure what is done for each package.

> use bootstrap, even if I don't want to (because it is opinionated)

Every design is built on opinions. Is there anything specifically that you do not like?

> use git, even if I don't want to (E.g., I want to use a different VC or a different cli tool)

Straight is written so that other version control backends can be implemented via a handful of functions.
No interested parties have done so.

> use emacs 25 or higher, even if I don't want to

Offering support for a 7 year old version of Emacs is generous IMO, but I understand there will always be versions we can't support.

> use very verbose elisp to update and manage packages

Cloning, building, and activating a package is often as simple as:

```emacs-lisp
(straight-use-package 'example)
```

or, with the built-in use-package integration:

```emacs-lisp
(use-package example) ; assuming straight-use-package-by-default is non-nil
(use-package example :straight t) ; assuming straight-use-package-by-default is nil
```

> I feel like this kind of development is too similar to webdev and to the npm ecosystem, which I'm not entirely fond of socially.

Too similar in what ways?

> For a systems design allegedly for ``emacs hackers'', this feels very constrained. Moreover, hacking does not refer to the basic usage of a system or customization thereof. That's just called using a computer.

Straight is designed to allow users to easily author, test, and contribute patches to upstream sources.
I believe that's where the sentiment "for the Emacs hacker" comes from. However, it is flexible enough to be used transparently by people who do not plan on working on elisp packages.

> What I would like to see as a user is a much less complex set of initial setup instructions, compatibility with package.el (so I don't need to redo everything I already have set up), and intended compatibility with older forms of emacs as well as other VCS etc

I happen to agree with you that the bootstrapping system is a bit complex.
I've tried to simplify it myself.

If you're aiming for compatibility with package.el, there has been recent work to install packages from their source repositories. However, it will not be available in Emacs versions < 29. I've addressed the comment about alternative VCS above.

Sorry to hear you don't find the project useful.
Thanks for your opinions.

**Comment by SylvianHemus** [comment]
Thanks for your reply; it's not that I don't think it's useful. It absolutely is 
Also It's Over, I have to use and updoot to this to handle stuff written in python for emacs
So I'm currently using it

**Comment by raxod502** [comment]
If you like, you can use the version from the first couple of commits: https://github.com/radian-software/straight.el/blob/a09b363b450f4032e2576541adc923bed4f65bf8/straight.el

It worked pretty well - I originally created `straight.el` because I thought `package.el` was too complicated and "installing an Elisp package is just compiling it and putting it on the load path, right?".

All the commits since then are fixing bugs, making optimizations, and adding support for people's use cases. That seems to be how it goes with software.
