### ISSUE TITLE
elpa straight mirror updates hang

### ISSUE THREAD

**Issue by minad** [radian-software/straight.el#1049]
The ELPA mirror lags behind. Recently it didn't update for three weeks. Is the automatic synchronization broken? The problem is that this breaks updates. I've observed this for the Compat package and it's downstream users.

**Comment by progfolio** [comment]
The mirror is intended to update daily.
It looks like @raxod502  recently committed some changes: https://github.com/radian-software/gnu-elpa-mirror/commit/ac3bc559c9ec1e0785bf80a83d8fb5ce245e181f

Also appears as if the last time it was updated was three days ago, so perhaps there's still an issue there.

**Comment by progfolio** [comment]
> The problem is that this breaks updates. I've observed this for the Compat package and it's downstream users.

As a workaround, anyone relying on Compat could install it directly from your github repostiory.

**Comment by minad** [comment]
@progfolio This is not really feasible to expect from the users since many packages depend on Compat now.

**Comment by progfolio** [comment]
It's a master of pasting the following before any packages which require compat:

```emacs-lisp
(straight-use-package '(compat :host github :repo "emacs-compat/compat"))
```

Personally, I try to minimize my reliance on mirrors, and I'm sure there are other users who would appreciate the simple solution. Feel free to link them to this comment.

An alternative solution which would be transparent to users while protecting them from future mirror failures would be to add compat to another ELPA such as MELPA.

Im not familiar with the gnu-elpa-mirror code base to diagnose and fix the problem myself,  so those solutions are the best I can offer until it is fixed.

**Comment by minad** [comment]
> It's a matter of pasting the following before any packages which require compat:

Of course, it is not a big deal in principle. The problem however is that breakage occurs for downstream packages like Magit, where the users are not even aware that Compat is used. I want to avoid such breakage in the first place. On the other hand most Straight users are experienced and as such they should be able to figure out updated-related issues caused by Straight themselves. But experience shows that this is unfortunately not the case, given the messages on the Magit and Compat issue trackers.

> An alternative solution which would be transparent to users while protecting them from future mirror failures would be to add compat to another ELPA such as MELPA.

That's not such a great option, since it could lead to more breakage down the road except if all the development happens in a separate development branch.

**Comment by minad** [comment]
@progfolio How do you solve the mirror problem with ELPA in Elpaca? For some reason Straight doesn't want to use the ELPA repositories directly (reliability, weird branches for packages, ...).

**Comment by progfolio** [comment]
> How do you solve the mirror problem with ELPA in Elpaca? 

Currently, I don't. Elpaca uses gnu-elpa-mirror. It's on my TODO list to support GNU ELPA directly.

> For some reason Straight doesn't want to use the ELPA repositories directly (reliability, weird branches for packages, ...).

I can only speak for myself here, but I've experienced intermittent reliability/speed issues when cloning repos hosted on savannah. The package-per-branch model is a pain, too.

I've not used it myself, but straight has an option to bypass the mirror. See the `straight-recipes-gnu-elpa-use-mirror` option. It would have to be set to `nil` prior to straight's bootstrapping snippet. 

The

**Comment by progfolio** [comment]
> Is the long term plan to deprecate Straight or to merge Elpaca back?

I don't plan on merging Elpaca back.
I've made several design decisions (e.g. only supporting git VCS) which are incompatible with straight.el's goals. I don't necessarily think straight.el needs to be deprecated either, due to these differences.

>  It would be better to support the ELPA repositories better in Straight directly and handle failures gracefully.

I agree there's room for improvement here.

> Would it make sense to set this option for now by default until the Straight mirror issues have been sorted out? Probably not since most users won't update Straight in the meantime? 

I don't think so. Just looking at the source for direct GNU ELPA support, it doesn't look like it will work properly to me. It assumes the packages directory is already populated, which is not the case after a fresh clone.

https://github.com/radian-software/straight.el/blob/3eca39dfc6797243ec7d1c6a7d45142407f73f88/straight.el#L3328-L3360

The following test (unless I'm missing something) confirms as much:

<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "straight.elpa-source"
  :preserve t
  :pre-bootstrap 
  (setq straight-recipes-gnu-elpa-use-mirror nil)
  :post-bootstrap 
  (straight-use-package
   '(compat :source gnu-elpa)))
```
</details>

- Test run at: `2023-02-07 10:23:46`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 56a8b6c 2023-02-04`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.8)
 of 2023-02-06`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa recipe → Cloning melpa...
Looking for gnu-elpa recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning elpa (for gnu-elpa)...
Looking for nongnu-elpa recipe → Cloning elpa (for gnu-elpa)...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 56a8b6c 2023-02-04
Packages:
"straight"                n/a                  develop 56a8b6c 2023-02-04
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master d0a5234d 2023-02-06
"gnu-elpa"                n/a                  main 5c276f056e 2023-01-31
"nongnu-elpa"             n/a                  main 85c7a060c6 2023-01-26
"el-get"                  melpa                master 17db7640 2023-01-28
"emacsmirror-mirror"      n/a                  master 03db6f7 2023-02-03

Error: (wrong-type-argument stringp nil)

```
</details>

I'll have to experiment to see what the best option is.

**Comment by raxod502** [comment]
Yeah, using GNU ELPA directly is a non-starter IMO. You're very welcome to try it, but I found it to be an utter disaster. The mirror has maintenance problems but at least I am the one getting alerted for failures rather than all the weird git submodule edge cases and build script errors of GNU ELPA happening on users' laptops.

The main reason for the recent outages being so long is simply that I am the only person maintaining the mirror at present, and even though I dedicated most/all of my available development time to fixing the mirror issue each week, it took almost a month to get through it all.

Anyway, as mentioned in the linked thread on GNU ELPA Mirror, I believe I've fixed the problem.
