### ISSUE TITLE
straight-pull-all vs auto-package-update.el

### ISSUE THREAD

**Issue by hongyi-zhao** [radian-software/straight.el#1072]
It seems the function `straight-pull-all` implemented in this package can at a large do the job by [auto-package-update.el](https://github.com/rranelli/auto-package-update.el), am I right?

**Comment by progfolio** [comment]
I believe we discussed this before here:

https://github.com/radian-software/straight.el/issues/832

In short, no. auto-package-update automatically updates packages periodically. straight-pull-all does not do that. You could write custom code to allow it to do that, but you'd also have to consider cases where intervention was needed (e.g. a merge couldn't be completed because the repository is in a dirty state, etc).
