### ISSUE TITLE
htmlz-mode does not follow elisp package format

### ISSUE THREAD

**Issue by danielkrajnik** [radian-software/straight.el#1091]
I've wasted days trying to understand why [htmlz-mode](https://github.com/0xekez/htmlz-mode/blob/master/htmlz.el) doesn't get loaded. Turned out that it wasn't prepared in package.el "format". 

Why on earth would you not just load that simple file? Why is some arbitrary format needed? Please spare others all the effort required to comprehend mess that is emacs "documentation".

**Comment by progfolio** [comment]
> I've wasted days trying to understand why [htmlz-mode](https://github.com/0xekez/htmlz-mode/blob/master/htmlz.el) doesn't get loaded. Turned out that it wasn't prepared in package.el "format".

I'm sorry to hear that.
It looks like there are several bugs in the way the package is authored:

1. It doesn't declare it's dependencies in the package meta-data header via Package-Requires.
2. It does not autoload any commands for the user.

> Why on earth would you not just load that simple file?

Packages generally aren't loaded by the package manager for a number of reasons.
The main reason is users usually want to choose *when* to load their packages. Forcing a load can slow down Emacs start-up time, increase memory usage, etc. That decision doesn't belong to the package manager (If you've seen `use-package` or similar init macros, that's their wheelhouse. They often integrate with package managers, too).

However, properly formatted packages are "activated" by straight.el (and other elisp package managers). Activation involves adding the package's directory to `load-path` so that `(require 'my-package)` will work. It also typically involves loading an autoloads file. The autolaods  being generated for htmlz-mode aren't helpful because the author didn't specify anything to autoload.

> Why is some arbitrary format needed?

The format is not arbitrary. It's well documented:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging.html

I'm sorry you ran into a package that does not follow that format, but that's a bug with the package, not the package manager. You should point out the issues detailed above to the package author on their issue tracker if you'd like to see them resolved.

**Comment by raxod502** [comment]
To add - `straight.el` isn't responsible for the Emacs packaging format. These were determined by the Emacs development team for `package.el` and you'd be best off providing feedback on emacs-devel if you have issues. In fact, `straight.el` is considerably more lax than the built-in package manager when it comes to formatting requirements for packages.

**Comment by danielkrajnik** [comment]
thanks for all the adivces, there's a lot to unpack here, but long story short, it was solved by adding a single
`;;;###autoload
 line to a `(define-minor-mode ...)` line...

**Comment by progfolio** [comment]
Glad to hear it.
That solves the problem 3 mentioned in my comment above.
They'll still want to add proper "Package-Requires" metadata as described here:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html

so that straight and other package managers can properly install any dependencies of the package. This will also allow them to remove the "require-package" function they defined in lieu of letting a package manager use that data.

**Comment by danielkrajnik** [comment]
True, I've mentioned it as well: https://github.com/0xekez/htmlz-mode/issues/3

**Comment by danielkrajnik** [comment]
Sorry for digging out this old thread, but I've just encountered an issue when trying to upgrade doom emacs:
```
 In repository "htmlz-mode", HEAD on default branch "master" has diverged from "origin/master"

         1) Abort
         2) Merge "origin/master" into "master"
         3) Rebase "master" onto "origin/master"
         4) Reset "master" to "origin/master"
         5) Magit log "master...origin/master" and open recursive edit
````

Sadly pressing neither 2 (merge) nor 3 (rebase) doesn't do anything, the only thing that works is resetting the package back to the original origin/master (4).

I just wanted to double check that committing changes to local repo is definitely supported by straight.el? If so, I will post this issue to the doom emacs maintainer.
