### ISSUE TITLE
How the autoload affect the `Integration of use-package`

### ISSUE THREAD

**Issue by ccqpein** [radian-software/straight.el#1152]
I found one issue yesterday. I gave an [issue](https://github.com/rust-lang/rust-mode/issues/527) with details. The `straight.el` cannot load the function if the function isn't `;;;###autoload`.

If I understand right, `rust-mode.el` needed to be loaded first to decide ([link](https://github.com/rust-lang/rust-mode/blob/master/rust-mode.el#L74-L76)) which file needed to require of `rust-mode`

And I think the `straight.el` doesn't load the `rust-mode.el` for finding the `rust-mode` function? I already find the solution in my side for fixing this issue by `load rust-mode.el in use-package :init step`. I just curious how the `straight.el` find the mode function and do we already have the solution of this situation? Thanks

**Comment by progfolio** [comment]
ccQpein ***@***.***> writes:

> I found one issue yesterday. I gave an issue with details. The 
> straight.el cannot load the
> function if the function isn't ;;;###autoload.
>
> If I understand right, rust-mode.el needed to be loaded first to 
> decide (link) which file
> needed to require of rust-mode
>
> And I think the straight.el doesn't load the rust-mode.el for 
> finding the rust-mode
> function? I already find the solution in my side for fixing this 
> issue by load rust-mode.el
> in use-package :init step. I just curious how the straight.el 
> find the mode function
> and do we already have the solution of this situation? Thanks
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this 
> thread.

If I understand the situation correctly, `rust-mode' is not 
autoloaded because it is defined in two separate files. Once in 
rust-prog-mode.el and once in rust-ts-mode.el. rust-mode.el is 
used to delegate the loading of one of those two files. To me this 
sounds like an inversion of the correct design. Ideally there 
would be a major mode which works without treesitter, and a minor 
mode which enables tree-sitter support. I know there was a long 
discussion on Emacs mailing thread about how tree-sitter support 
should be integrated, but I don't know if the approach rust-mode 
is taking is the recommended approach.

In any case, straight does nothing special in this situation.
As you noted, you would need to either autoload rust-mode yourself 
(you may be able to finagle something with use-package's :commands 
keyword), or load rust-mode.el when you see fit.

Does that help?

**Comment by ccqpein** [comment]
@progfolio Thanks, it is help!
