### ISSUE TITLE
AUCTeX mirror no longer contains `tex-site.el`

### ISSUE THREAD

**Issue by TOTBWF** [radian-software/straight.el#1160]
In #240, a full mirror of ELPA was created to work around to `auctex` not shipping build artifacts. It seems that https://github.com/emacs-straight/auctex/commit/5471db4ee2fcd5ad023611b188d9edce068dc5ea removed the build artifacts for some reason, which means that `(straight-use-package auctex)` now fails due to `tex-site.el` being missing.

**Comment by raxod502** [comment]
Confirmed, and I ran into this today while upgrading.

This change from upstream sure looks relevant:

![image](https://github.com/radian-software/straight.el/assets/6559064/cebc1c14-6859-4d05-9984-905a8cc712d8)

Guess we have to figure out (again) what GNU ELPA is doing, and replicate that (again).

**Comment by raxod502** [comment]
Ok, that comes from this upstream commit which deletes `tex-site.el`: https://git.savannah.gnu.org/cgit/auctex.git/commit/?h=main&id=6b3e109cd46c5c2d1d1379891bf79cf934246789 which was pushed on 2024-04-19. 

Confirmed that GNU ELPA build system is somehow generating `tex-site.el` though - https://elpa.gnu.org/devel/auctex.html download of [auctex-14.0.4.0.20240427.91120.tar](https://elpa.gnu.org/devel/auctex-14.0.4.0.20240427.91120.tar) gives an archive that does contain `tex-site.el`, and it is dated 2024-04-27.

**Comment by raxod502** [comment]
Well [that'll do it](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/elpa-packages?h=9f03484eee87d0b311fbf06de4ce6a96cde160cc#n76), there is a new `:make` parameter, so I just have to update GNU ELPA Mirror to run the command given there if present.

**Comment by raxod502** [comment]
I've dug into this a bunch and it turns out that you have to `make build/<package>` which is a step we were not doing. But then it turns out that this has a billion dependencies on random things like Markdown converters and TeX Live and other undocumented things, and it also doesn't work without various hacks to the source code to do things like bind-mount `/var` and and and...

A stupider yet far superior option is to rewrite GNU ELPA Mirror to just pull the published tarballs. Then we don't ever have to maintain this again.

**Comment by raxod502** [comment]
Pushed https://github.com/radian-software/gnu-elpa-mirror/commit/accb598ef5dcc593412706add48749cfe3f7941a and rebuilding now. You can see https://github.com/emacs-straight/auctex/blob/a5552370bde473b1043f20a6385f89122af9af7d/tex-site.el is available after the latest commit.

**Comment by TOTBWF** [comment]
Thanks for fixing this so quickly, really appreciate it 🙂
