### ISSUE TITLE
How to get the list of installed packages?

### ISSUE THREAD

**Issue by ezchi** [radian-software/straight.el#958]
Is there any way to get the list of installed packages?

**Comment by progfolio** [comment]
It depends what you mean by "installed". Are you asking for a list of packages:

- which were activated in the current Emacs session by straight.el?
- which are on disk in the straight/repos/ directory?
- which are on disk in the straight/build/ directory?

Depending on what you're after these could be slightly different lists.
This should cover most packages, but it does exclude packages which have no dependencies:

```emacs-lisp
(cl-sort
 (delete-dups (flatten-tree (straight-dependents "emacs")))
 #'string<)
```

**Comment by progfolio** [comment]
And this should cover the case for packages which do not declare a min Emacs version:

```emacs-lisp
(cl-sort
 (delete-dups (flatten-tree
               (mapcar (lambda (it) (list it (straight-dependencies it)))
               (straight-dependents "emacs"))))
 #'string<)
 ```

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
